import type { Member } from "@/types/member";

export interface ProjectTimeline {
  id: string;
  title: string;
  description: string;
  period: string;
  date: string;
  technologies: string[];
  status: "completed" | "ongoing" | "planned";
  type: "web" | "mobile" | "ai" | "infrastructure" | "other";
}

export const members: Member[] = [
  {
    id: "alex-kim",
    name: "Alex Kim",
    role: "Full Stack Developer",
    specialties: ["frontend", "backend"],
    bio: "웹 개발의 모든 영역을 아우르는 풀스택 개발자입니다. React와 Node.js를 주력으로 하며, 사용자 경험을 중시하는 개발을 추구합니다.",
    avatar: "/placeholder.svg?height=200&width=200",
    github: "https://github.com/alexkim",
    linkedin: "https://linkedin.com/in/alexkim",
    portfolio: "https://alexkim.dev",
    email: "alex@example.com",
    skills: ["React", "Next.js", "Node.js", "TypeScript", "PostgreSQL", "AWS"],
    projects: [
      "E-commerce Platform",
      "Task Management App",
      "Real-time Chat System",
    ],
    experience:
      "5년차 개발자로 스타트업부터 대기업까지 다양한 환경에서 경험을 쌓았습니다.",
    location: "Seoul, Korea",
    projectTimeline: [
      {
        id: "1",
        title: "개인 포트폴리오 웹사이트",
        description:
          "React와 Three.js를 활용한 인터랙티브 포트폴리오 사이트 개발",
        period: "2022.01 - 2022.03",
        date: "2022-01",
        technologies: ["React", "Three.js", "GSAP", "Styled Components"],
        status: "completed",
        type: "web",
      },
      {
        id: "2",
        title: "E-commerce Platform",
        description:
          "풀스택 온라인 쇼핑몰 플랫폼 개발. 결제 시스템과 관리자 대시보드 포함",
        period: "2022.06 - 2023.02",
        date: "2022-06",
        technologies: ["Next.js", "Node.js", "PostgreSQL", "Stripe", "AWS"],
        status: "completed",
        type: "web",
      },
      {
        id: "3",
        title: "Task Management App",
        description: "팀 협업을 위한 실시간 태스크 관리 애플리케이션",
        period: "2023.03 - 2023.08",
        date: "2023-03",
        technologies: ["React", "Socket.io", "Express", "MongoDB", "Redis"],
        status: "completed",
        type: "web",
      },
      {
        id: "4",
        title: "Real-time Chat System",
        description: "WebSocket 기반 실시간 채팅 시스템 및 화상 통화 기능",
        period: "2023.09 - 2024.01",
        date: "2023-09",
        technologies: [
          "Next.js",
          "WebRTC",
          "Socket.io",
          "TypeScript",
          "Docker",
        ],
        status: "completed",
        type: "web",
      },
      {
        id: "5",
        title: "AI 기반 추천 시스템",
        description: "머신러닝을 활용한 개인화 추천 엔진 개발",
        period: "2024.02 - 현재",
        date: "2024-02",
        technologies: [
          "Python",
          "TensorFlow",
          "FastAPI",
          "React",
          "PostgreSQL",
        ],
        status: "ongoing",
        type: "ai",
      },
    ],
  },
  {
    id: "mike-park",
    name: "Mike Park",
    role: "Backend Engineer",
    specialties: ["backend", "devops"],
    bio: "확장 가능한 백엔드 시스템과 클라우드 인프라 구축을 전문으로 하는 엔지니어입니다.",
    avatar: "/placeholder.svg?height=200&width=200",
    github: "https://github.com/mikepark",
    linkedin: "https://linkedin.com/in/mikepark",
    email: "mike@example.com",
    skills: ["Python", "Django", "FastAPI", "Docker", "Kubernetes", "GCP"],
    projects: [
      "Microservices Architecture",
      "CI/CD Pipeline",
      "Data Processing System",
    ],
    experience: "6년차 백엔드 엔지니어로 대용량 트래픽 처리 경험이 풍부합니다.",
    location: "Busan, Korea",
    projectTimeline: [
      {
        id: "1",
        title: "레거시 시스템 마이그레이션",
        description: "모놀리식 아키텍처를 마이크로서비스로 전환",
        period: "2021.09 - 2022.05",
        date: "2021-09",
        technologies: [
          "Python",
          "Django",
          "Docker",
          "Kubernetes",
          "PostgreSQL",
        ],
        status: "completed",
        type: "infrastructure",
      },
      {
        id: "2",
        title: "Microservices Architecture",
        description: "확장 가능한 마이크로서비스 아키텍처 설계 및 구현",
        period: "2022.06 - 2023.01",
        date: "2022-06",
        technologies: ["FastAPI", "Docker", "Kubernetes", "Redis", "RabbitMQ"],
        status: "completed",
        type: "infrastructure",
      },
      {
        id: "3",
        title: "CI/CD Pipeline",
        description: "자동화된 배포 파이프라인 구축 및 모니터링 시스템",
        period: "2023.02 - 2023.07",
        date: "2023-02",
        technologies: [
          "Jenkins",
          "GitLab CI",
          "Terraform",
          "Prometheus",
          "Grafana",
        ],
        status: "completed",
        type: "infrastructure",
      },
      {
        id: "4",
        title: "Data Processing System",
        description: "대용량 데이터 처리를 위한 실시간 스트리밍 시스템",
        period: "2023.08 - 2024.03",
        date: "2023-08",
        technologies: [
          "Apache Kafka",
          "Apache Spark",
          "Python",
          "Elasticsearch",
        ],
        status: "completed",
        type: "infrastructure",
      },
      {
        id: "5",
        title: "클라우드 네이티브 플랫폼",
        description: "GCP 기반 서버리스 아키텍처 구축",
        period: "2024.04 - 현재",
        date: "2024-04",
        technologies: [
          "GCP",
          "Cloud Functions",
          "Cloud Run",
          "Pub/Sub",
          "BigQuery",
        ],
        status: "ongoing",
        type: "infrastructure",
      },
    ],
  },
  {
    id: "jenny-choi",
    name: "Jenny Choi",
    role: "Frontend Developer",
    specialties: ["frontend"],
    bio: "모던 프론트엔드 기술을 활용해 인터랙티브하고 성능 최적화된 웹 애플리케이션을 개발합니다.",
    avatar: "/placeholder.svg?height=200&width=200",
    github: "https://github.com/jennychoi",
    linkedin: "https://linkedin.com/in/jennychoi",
    portfolio: "https://jennychoi.dev",
    email: "jenny@example.com",
    skills: [
      "React",
      "Vue.js",
      "TypeScript",
      "Tailwind CSS",
      "Three.js",
      "WebGL",
    ],
    projects: [
      "3D Portfolio Website",
      "Real-time Dashboard",
      "Progressive Web App",
    ],
    experience: "3년차 프론트엔드 개발자로 창의적인 웹 경험 구현을 좋아합니다.",
    location: "Seoul, Korea",
    projectTimeline: [
      {
        id: "1",
        title: "반응형 랜딩 페이지",
        description: "Vue.js와 GSAP을 활용한 인터랙티브 랜딩 페이지",
        period: "2022.03 - 2022.05",
        date: "2022-03",
        technologies: ["Vue.js", "GSAP", "Sass", "Webpack"],
        status: "completed",
        type: "web",
      },
      {
        id: "2",
        title: "3D Portfolio Website",
        description: "Three.js를 활용한 3D 인터랙티브 포트폴리오 웹사이트",
        period: "2022.08 - 2022.12",
        date: "2022-08",
        technologies: ["React", "Three.js", "WebGL", "Framer Motion"],
        status: "completed",
        type: "web",
      },
      {
        id: "3",
        title: "Real-time Dashboard",
        description: "데이터 시각화를 위한 실시간 대시보드 애플리케이션",
        period: "2023.01 - 2023.06",
        date: "2023-01",
        technologies: ["React", "D3.js", "Socket.io", "Chart.js", "TypeScript"],
        status: "completed",
        type: "web",
      },
      {
        id: "4",
        title: "Progressive Web App",
        description: "오프라인 지원 PWA 및 모바일 최적화",
        period: "2023.07 - 2023.12",
        date: "2023-07",
        technologies: ["Next.js", "PWA", "Service Worker", "IndexedDB"],
        status: "completed",
        type: "web",
      },
      {
        id: "5",
        title: "WebGL 게임 엔진",
        description: "브라우저 기반 2D/3D 게임 엔진 개발",
        period: "2024.01 - 현재",
        date: "2024-01",
        technologies: ["TypeScript", "WebGL", "Canvas API", "Web Workers"],
        status: "ongoing",
        type: "web",
      },
    ],
  },
  {
    id: "david-jung",
    name: "David Jung",
    role: "Mobile Developer",
    specialties: ["mobile"],
    bio: "React Native와 Flutter를 활용한 크로스플랫폼 모바일 앱 개발 전문가입니다.",
    avatar: "/placeholder.svg?height=200&width=200",
    github: "https://github.com/davidjung",
    linkedin: "https://linkedin.com/in/davidjung",
    email: "david@example.com",
    skills: [
      "React Native",
      "Flutter",
      "Swift",
      "Kotlin",
      "Firebase",
      "App Store",
    ],
    projects: ["Food Delivery App", "Fitness Tracking App", "Social Media App"],
    experience: "4년차 모바일 개발자로 다수의 앱스토어 출시 경험이 있습니다.",
    location: "Incheon, Korea",
    projectTimeline: [
      {
        id: "1",
        title: "날씨 앱",
        description: "위치 기반 실시간 날씨 정보 앱",
        period: "2021.11 - 2022.02",
        date: "2021-11",
        technologies: ["React Native", "OpenWeather API", "AsyncStorage"],
        status: "completed",
        type: "mobile",
      },
      {
        id: "2",
        title: "Food Delivery App",
        description: "음식 주문 및 배달 추적 모바일 애플리케이션",
        period: "2022.03 - 2022.09",
        date: "2022-03",
        technologies: ["Flutter", "Firebase", "Google Maps", "Stripe"],
        status: "completed",
        type: "mobile",
      },
      {
        id: "3",
        title: "Fitness Tracking App",
        description: "운동 기록 및 건강 관리 앱",
        period: "2022.10 - 2023.04",
        date: "2022-10",
        technologies: ["React Native", "HealthKit", "SQLite", "Chart.js"],
        status: "completed",
        type: "mobile",
      },
      {
        id: "4",
        title: "Social Media App",
        description: "사진 공유 및 소셜 네트워킹 플랫폼",
        period: "2023.05 - 2023.12",
        date: "2023-05",
        technologies: [
          "Flutter",
          "Firebase",
          "Cloud Storage",
          "Push Notifications",
        ],
        status: "completed",
        type: "mobile",
      },
      {
        id: "5",
        title: "AR 쇼핑 앱",
        description: "증강현실 기반 가구 배치 쇼핑 앱",
        period: "2024.01 - 현재",
        date: "2024-01",
        technologies: ["React Native", "ARCore", "ARKit", "3D Models"],
        status: "ongoing",
        type: "mobile",
      },
    ],
  },
  {
    id: "lisa-wang",
    name: "Lisa Wang",
    role: "AI Engineer",
    specialties: ["ai", "backend"],
    bio: "머신러닝과 딥러닝을 활용한 AI 솔루션 개발과 데이터 분석을 전문으로 합니다.",
    avatar: "/placeholder.svg?height=200&width=200",
    github: "https://github.com/lisawang",
    linkedin: "https://linkedin.com/in/lisawang",
    email: "lisa@example.com",
    skills: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "Scikit-learn",
      "OpenAI API",
      "MLOps",
    ],
    projects: [
      "Chatbot System",
      "Image Recognition App",
      "Recommendation Engine",
    ],
    experience:
      "5년차 AI 엔지니어로 다양한 도메인의 AI 프로젝트를 수행했습니다.",
    location: "Seoul, Korea",
    projectTimeline: [
      {
        id: "1",
        title: "감정 분석 모델",
        description: "텍스트 기반 감정 분석 딥러닝 모델 개발",
        period: "2021.08 - 2021.12",
        date: "2021-08",
        technologies: ["Python", "TensorFlow", "BERT", "Transformers"],
        status: "completed",
        type: "ai",
      },
      {
        id: "2",
        title: "Chatbot System",
        description: "자연어 처리 기반 고객 서비스 챗봇 시스템",
        period: "2022.01 - 2022.07",
        date: "2022-01",
        technologies: ["Python", "OpenAI API", "FastAPI", "PostgreSQL"],
        status: "completed",
        type: "ai",
      },
      {
        id: "3",
        title: "Image Recognition App",
        description: "컴퓨터 비전 기반 객체 인식 및 분류 시스템",
        period: "2022.08 - 2023.02",
        date: "2022-08",
        technologies: ["PyTorch", "OpenCV", "YOLO", "Flask", "Docker"],
        status: "completed",
        type: "ai",
      },
      {
        id: "4",
        title: "Recommendation Engine",
        description: "협업 필터링 기반 개인화 추천 시스템",
        period: "2023.03 - 2023.09",
        date: "2023-03",
        technologies: ["Python", "Scikit-learn", "Apache Spark", "Redis"],
        status: "completed",
        type: "ai",
      },
      {
        id: "5",
        title: "MLOps 파이프라인",
        description: "머신러닝 모델 배포 및 모니터링 시스템",
        period: "2023.10 - 현재",
        date: "2023-10",
        technologies: [
          "MLflow",
          "Kubeflow",
          "Docker",
          "Kubernetes",
          "Prometheus",
        ],
        status: "ongoing",
        type: "ai",
      },
    ],
  },
  {
    id: "tom-lee",
    name: "Tom Lee",
    role: "DevOps Engineer",
    specialties: ["devops", "backend"],
    bio: "클라우드 인프라와 자동화를 통해 개발팀의 생산성을 극대화하는 DevOps 엔지니어입니다.",
    avatar: "/placeholder.svg?height=200&width=200",
    github: "https://github.com/tomlee",
    linkedin: "https://linkedin.com/in/tomlee",
    email: "tom@example.com",
    skills: [
      "AWS",
      "Terraform",
      "Jenkins",
      "Docker",
      "Kubernetes",
      "Monitoring",
    ],
    projects: [
      "Infrastructure as Code",
      "Automated Deployment",
      "Monitoring System",
    ],
    experience: "4년차 DevOps 엔지니어로 다양한 규모의 인프라를 관리했습니다.",
    location: "Seoul, Korea",
    projectTimeline: [
      {
        id: "1",
        title: "AWS 인프라 구축",
        description: "Terraform을 활용한 AWS 클라우드 인프라 자동화",
        period: "2021.06 - 2021.10",
        date: "2021-06",
        technologies: ["AWS", "Terraform", "CloudFormation", "VPC"],
        status: "completed",
        type: "infrastructure",
      },
      {
        id: "2",
        title: "Infrastructure as Code",
        description: "코드로 관리하는 인프라 구축 및 버전 관리",
        period: "2021.11 - 2022.04",
        date: "2021-11",
        technologies: ["Terraform", "Ansible", "GitLab CI", "AWS"],
        status: "completed",
        type: "infrastructure",
      },
      {
        id: "3",
        title: "Automated Deployment",
        description: "Jenkins 기반 자동화된 배포 파이프라인",
        period: "2022.05 - 2022.11",
        date: "2022-05",
        technologies: ["Jenkins", "Docker", "Kubernetes", "Helm"],
        status: "completed",
        type: "infrastructure",
      },
      {
        id: "4",
        title: "Monitoring System",
        description: "Prometheus와 Grafana를 활용한 모니터링 시스템",
        period: "2022.12 - 2023.06",
        date: "2022-12",
        technologies: ["Prometheus", "Grafana", "AlertManager", "ELK Stack"],
        status: "completed",
        type: "infrastructure",
      },
      {
        id: "5",
        title: "멀티 클라우드 전략",
        description: "AWS, GCP, Azure 멀티 클라우드 환경 구축",
        period: "2023.07 - 현재",
        date: "2023-07",
        technologies: ["AWS", "GCP", "Azure", "Terraform", "Kubernetes"],
        status: "ongoing",
        type: "infrastructure",
      },
    ],
  },
];

export function getMemberById(id: string): Member | undefined {
  return members.find((member) => member.id === id);
}

export function getMembersBySpecialty(specialty: string): Member[] {
  if (specialty === "all") return members;
  return members.filter((member) => member.specialties.includes(specialty));
}
